# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2023-02-22 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0226_osfuser_is_data_steward'),
        ('osf', '0226_alter_filelog_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='data_steward_old_permission',
            field=models.CharField(choices=[('NULL', None), ('READ', 'read'), ('WRITE', 'write'), ('ADMIN', 'admin')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contributor',
            name='is_data_steward',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
