# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2023-06-09 12:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0227_ensure_schema_and_reports'),
        ('osf', '0226_ensure_schema_and_reports'),
    ]

    operations = [
    ]
