# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2023-06-17 10:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0228_merge_20230609_1243'),
        ('osf', '0228_ensure_schema_and_reports'),
    ]

    operations = [
    ]
