# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2023-07-09 22:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0229_merge_20230617_1021'),
        ('osf', '0230_auto_20230518_0407'),
    ]

    operations = [
    ]
