# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2023-08-24 12:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0231_merge_20230709_2236'),
        ('osf', '0229_ensure_schema_and_reports'),
    ]

    operations = [
    ]
