# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2023-09-28 04:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0232_merge_20230824_1203'),
        ('osf', '0227_auto_20230222_1029'),
    ]

    operations = [
    ]
